name: Publish image to artifactory
# on:
#   pull_request:
#     branches:
#       - master
#     types: [closed]
on: [push, pull_request]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t rhm-arcade .

      - name: Tag image
        run: docker tag "rmh-arcade" "${{ secrets.REGISTRY_REPO }}.${{ secrets.REGISTRY_HOST }}/rhm-arcade:latest"

      - name: Login to artifactory
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_REPO }}.${{ secrets.REGISTRY_HOST }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Push image to Artifactory
        run: docker push "${{ secrets.REGISTRY_REPO }}.${{ secrets.REGISTRY_HOST }}/rhm-arcade"
